############################################################################################
#
# Referencias: https://medium.com/@yurii.slobodianiuk/introduction-to-json-in-oracle-database-bb67b35f5edd
#              https://blogs.oracle.com/coretec/data-in-json-format-with-oracle-functions-and-tools
#              https://www.tutorialesprogramacionya.com/jsonya/tema22.html
#
############################################################################################

# GENERAL

# Una API REST (o RESTful) es una interfaz digital que permite que dos sistemas de software se comuniquen entre sí a través de internet usando el protocolo HTTP.
# API (Application Programming Interface): Un conjunto de reglas que permite a una aplicación pedir datos o acciones a otra.
# REST (Representational State Transfer): Un estilo de arquitectura de software que define cómo debe estructurarse la comunicación.
# RESTful: Es el adjetivo que se usa para describir un servicio web o una API que cumple estrictamente con los principios de REST.
# La comunicación funciona mediante peticiones y respuestas usando los métodos estándar de HTTP (conocidos como operaciones CRUD):
# 	GET: Para leer u obtener información (por ejemplo, buscar el perfil de un usuario).
# 	POST: Para crear un recurso nuevo (por ejemplo, registrar una cuenta nueva).
# 	PUT: Para actualizar un registro existente.
# 	DELETE: Para eliminar datos

# Para que una API sea considerada RESTful, debe seguir normas como:
#   Cliente-servidor: El frontend (la interfaz visual) y el backend (el servidor y la base de datos) están totalmente separados.
#   Sin estado (Stateless): Cada petición del cliente debe contener toda la información necesaria para que el servidor la entienda; el servidor no guarda datos de sesiones anteriores en la memoria local.
#   Caché: Las respuestas deben indicar si pueden guardarse temporalmente para acelerar la velocidad de carga

# JSON (JavaScript Object Notation) es un formato basado en texto ligero usado para almacenar e intercambiar datos.
# JSON es un componente vita de las integraciones API. Con llamadas REST o desarrollando servicios web, es esencial entender como trabajar con JSON.
# JSON representa datos como key-value y soporta estructuras de datos como objetos (diccionarios) y arrays (listas).
# JSON juega un papel principal en REST (Representational State Transfer) APIs cimo el formato primario para intercambio de datos entre clientes y servidores.
# Cuando un cliente hace una petición (GET, POST, PUT, DELETE), el servidor responde con datos formateados en JSON, que el cliente puede parsear y procesar.
# Comparado con XML, JSON es más compacto y rápido de parsear, mejorando el rendimiento en aplicaciones web.

# Oracle Database ofrece soporte nativo para JSON desde la versión 12c
# Se puede guardar JSON en columnas de tipo VARCHAR2, CLOB, BLOB.
# Desde Oracle 21c existe un tipo de dato específico JSON.

##########################
# TABLAS/REGISTROS EJEMPLO
##########################

# Tabla ejemplo 1

		CREATE TABLE productos (
			id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			nombre VARCHAR2(100),
			datos CLOB CHECK (datos IS JSON)
		);

		INSERT INTO productos (nombre, datos) VALUES
		('Teclado', '{"codigo":101,"precio":1200.50,"disponible":true,"tags":["periférico","oferta"]}');

		INSERT INTO productos (nombre, datos) VALUES
		('Mouse', '{"codigo":102,"precio":850.75,"disponible":false}');

# Tabla ejemplo 2

		CREATE TABLE tiendas_inventario (
			id          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			nombre_sede VARCHAR2(100),
			datos_json  VARCHAR2(4000),
			CONSTRAINT  ensure_json CHECK (datos_json IS JSON) -- Chequea que el valor introducido sea un json
		);

		INSERT INTO tiendas_inventario (nombre_sede, datos_json) VALUES (
			'Sede Central Madrid',
			'{
				"tienda": "Madrid Centro",
				"encargado": "Carlos Pérez",
				"productos": [
					{"id_prod": 101, "nombre": "Teclado Mecánico", "precio": 45.99, "stock": 15},
					{"id_prod": 102, "nombre": "Ratón Inalámbrico", "precio": 25.50, "stock": 30},
					{"id_prod": 103, "nombre": "Monitor 24 pulgadas", "precio": 149.99, "stock": 8}
				]
			}'
		);

		INSERT INTO tiendas_inventario (nombre_sede, datos_json) VALUES (
			'Sede Sucursal Barcelona',
			'{
				"tienda": "Barcelona Norte",
				"encargado": "Ana Gómez",
				"productos": [
					{"id_prod": 101, "nombre": "Teclado Mecánico", "precio": 47.00, "stock": 5},
					{"id_prod": 104, "nombre": "Auriculares Gamer", "precio": 59.90, "stock": 12}
				]
			}'
		);

###################
# CONSULTA
###################


# JSON_VALUE: Extraer valores escalares 

SELECT 
    nombre,
    JSON_VALUE(datos, '$.codigo') AS codigo,
    JSON_VALUE(datos, '$.precio') AS precio
FROM productos;

SELECT nombre, JSON_VALUE(datos, '$.precio') AS precio
FROM productos
WHERE JSON_VALUE(datos, '$.precio') > 1000;


# JSON_QUERY: Extraer objetos/arrays

SELECT JSON_QUERY(datos, '$.tags') AS tags
FROM productos
WHERE nombre = 'Teclado';

# JSON_TABLE: Consultar arrays JSON para extraer elementos individuales / Extraer contenido de un ARRAY

SELECT t.nombre, jt.codigo AS codigo, jt.precio as precio
FROM productos t,
JSON_TABLE(t.datos, '$'
        COLUMNS (
            codigo VARCHAR2(50) PATH '$.codigo',
            precio NUMBER       PATH '$.precio'
        )
     ) jt
WHERE t.nombre = 'Teclado';

SELECT 
    t.id AS tabla_id,
    t.nombre_sede,
    j.tienda_json,
    j.encargado,
    j.producto_id,
    j.producto_nombre,
    j.precio,
    j.stock
FROM 
    tiendas_inventario t,
    JSON_TABLE(t.datos_json, '$'
        COLUMNS (
            tienda_json VARCHAR2(50) PATH '$.tienda',
            encargado   VARCHAR2(50) PATH '$.encargado',
            -- Desglosamos el array de productos en filas
            NESTED PATH '$.productos[*]' COLUMNS (
                producto_id     NUMBER        PATH '$.id_prod',
                producto_nombre VARCHAR2(100) PATH '$.nombre',
                precio          NUMBER        PATH '$.precio',
                stock           NUMBER        PATH '$.stock'
            )
        )
    ) j;


###################
# ACTUALIZACION
###################

# JSON_MERGEPATCH

UPDATE productos
SET datos = JSON_MERGEPATCH(datos, '{"precio": 900}')
WHERE nombre = 'Mouse';


# JSON_TRANSFORM (21c+)

UPDATE productos
SET datos = JSON_TRANSFORM(datos, SET '$.precio' = 1500.6)
WHERE nombre = 'Teclado';

###################
# BORRADO
###################

UPDATE productos
SET datos = JSON_TRANSFORM(datos, REMOVE '$.tags')
WHERE nombre = 'Teclado';

###################
# GENERAR JSON
###################

# Generar JSON desde una consulta
#   NOTA: JSON_OBJECT puede devolver VARCHAR2 or CLOB. Por defecto devuelve VARCHAR2, que puede generar una excepcion overflow exception si el tamaño del objeto supera los 4000 bytes (or 32000 bytes).

SELECT JSON_OBJECT(
    'id' VALUE id,
    'nombre' VALUE nombre,
    'datos' VALUE datos
) AS producto_json
FROM productos;

# Agrupar los valores de filas de una consulta SQL y convertirlos en una única matriz JSON

SELECT JSON_ARRAYAGG(e.first_name ORDER BY e.first_name) AS employee_array 
FROM employees e 
WHERE e.department_id = 20;

#############
# INDICES
#############
# Oracle soporta functional indexes para acelerar consultas sobre JSON.

CREATE INDEX idx_precio_json 
ON productos (JSON_VALUE(datos, '$.precio')); -- Consultas por precio serán más rápidas.

#########################
# TRANSFORMAR XML A JSON
#########################

select XMLType('<person><name>Martin</name><id>1234</id></person>') as Dato_XML, 
       XMLTOJSON(XMLType('<person><name>Martin</name><id>1234</id></person>')) Dato_JSON
from dual;

####################################
#  JSON DESDE PL/SQL (JSON_OBJECT_T)
####################################

# JSON_OBJECT_T: Puede usarse para generar y parsear datos JSON.
# Uso directo: 
#   Crear nuevo par key-value usando el tipo JSON_OBJECT_T e invocando al metodo put. 
#   Crear nuevo array usando el tipo JSON_ARRAY_T.
# El parseado es incluso más directo: Pasa los datos JSON a la función parse y JSON_OBJECT_T la maneja por ti. Una vez parseado puedes acceder a los datos usando keys.
# Usando JSON_OBJECT_T no se necesitan paths, sin embargo se necesita logica adicional para almacenar los datos del JSON parseado en una tabla.

DECLARE
  l_json JSON_OBJECT_T;
  l_courses JSON_ARRAY_T;
  l_addresses JSON_OBJECT_T;
  l_addresses_arr JSON_ARRAY_T;
  
  l_keys JSON_KEY_LIST;
  l_value JSON_ARRAY_T;
   l_json_object JSON_OBJECT_T;
BEGIN
  -- Create a new object.
  l_json := JSON_OBJECT_T();

  -- Add a new element to the object.
  l_json.put('name', 'Robert');
  l_json.put('age', 23);
  l_json.put('isStudent', 'false');

  -- Create courses array
  l_courses := JSON_ARRAY_T();
  l_courses.append('Math');
  l_courses.append('Science');
  l_courses.append('Music');
  -- Add courses to object
  l_json.put('courses', l_courses);

  -- Create addresses array
  l_addresses_arr := JSON_ARRAY_T();
  -- Create addresses object
  l_addresses := JSON_OBJECT_T();
  l_addresses.put('city','New York');
  l_addresses.put('zip','10001');
  -- Add to array
  l_addresses_arr.append(l_addresses);
  -- Create addresses object
  l_addresses := JSON_OBJECT_T();
  l_addresses.put('city','Boston');
  l_addresses.put('zip','02108');
  -- Add to array
  l_addresses_arr.append(l_addresses);
  -- Add addresses to object
  l_json.put('addresses', l_addresses_arr);

  
  DBMS_OUTPUT.put_line(l_json.stringify);

  DBMS_OUTPUT.put_line('Sacamos los valores:'); 

 l_json_object := JSON_OBJECT_T.parse(l_json.stringify);
  l_keys := l_json_object.get_keys;
  FOR i IN 1..l_keys.COUNT LOOP
    IF l_json_object.get_Type(l_keys(i)) = 'SCALAR' THEN
      dbms_output.put_line(l_keys(i) || ':' || l_json_object.get_String(l_keys(i)));
    ELSE -- Array
      l_value := l_json_object.get_Array(l_keys(i));
      dbms_output.put_line(l_value.stringify);
    END IF;
  END LOOP;

END;

